### PR TITLE
Add argument to be able to exclude directories

### PR DESCRIPTION
**Pull request by davidramosweb**
This merges request will prevent the `.git` and `node_modules` directories from being copied.

### CODE REVIEW

**Comment by slavivanov** [comment]
Hey, thanks for the PR.
Aren't the node_modules required for the functioning of the copied module?

**Comment by davidramosweb** [comment]
> Hey, thanks for the PR.
> Aren't the node_modules required for the functioning of the copied module?

True, for some packages node_modules is necessary. I have changed the code so that they can be excluded according to the needs of each package :)

**Comment by slavivanov** [comment]
Sweet, thanks!

**Comment by davidramosweb** [comment]
> Sweet, thanks!

You're welcome, it's a pleasure.

PS: could you update the package in npm?

https://www.npmjs.com/package/npm-link-by-copy

Thanks.

**Comment by slavivanov** [comment]
Done.

**Pull request merged**
